### ISSUE TITLE
Breaking audio managemenet completely

### ISSUE THREAD

**Issue by smileBeda** [lemmyg/t2-apple-audio-dsp#13]
I just noticed that following https://wiki.t2linux.org/guides/audio-config/#internal-microphones-dsp-configuration, which leads to this repo and suggests to install the configs of this repo, completely nukes audio on mac:
- no more settings available at all
- no more audio available / working at all

As soon the configs are removed things work again.

**Comment by lemmyg** [comment]
Hello,
if you are trying to install this config in a T2 mac please ask in https://discord.com/channels/595304521857630254 at your distribution group. Note that only works with t2 macs. Please be as descriptive as possible explaining which model and how are you installing it.
Thanks
